### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by holodny** [pavansolapure/opencodez-samples#1]
Hi Pavan, thanks for sharing this awesome project!  I'm running it on Linux and ran into issues with the database references switching between User and USER (I think this might not be an issue on Windows?).  For Linux, I named the table "User" and made all references match "User" (first letter capitalized).  Also, the totalRecords being part of the userModel seems to be causing an error Unknown column 'user0_.totalrecords'.  

I made all references to totalRecords the same capitalization-wise (as "totalRecords") and then I added a "totalRecords" field to the User table as a workaround because "updatable=false, insertable=false" (in the @Column annotation for totalRecords in the User class) doesn't seem to be working for me and I get error **Unknown column 'user0_.totalRecords' in 'field list'** when trying to enter a record.  I tried using @Transient with the declaration for totalRecords in class User and that worked for insertion but not for looking at the datatables paginated report, since then totalRecords didn't persist.

**Comment by pavansolapure** [comment]
Thanks for the update!
This I was able to resolve by simply swapping the objects. Now I used UserModel class to do rendering.
As this object is not directly connected to User table, we can keep total records here. On top of swapping, I changed queries little bit accordingly.

You can pull the latest code and try out.

Let me know if you still see the same issue.

FYI - I did not face any issue regarding User/USER on windows.


Thanks
Pavan
